---
description: Ingest pipeline for items
processors:
  - set:
      field: event.dataset
      value: connector.items
  - set:
      field: "@timestamp"
      value: "{{_ingest.timestamp}}"
  - set:
      field: ecs.version
      value: "8.0.0"
  - set:
      field: message
      value: "nothing important"
  - set: 
      field: input.type
      value: httpjson

