---
description: Ingest pipeline for items
processors:
  - rename:
      field: item.id
      target_field: id
  - rename:
      field: item.name
      target_field: name
  - rename:
      field: item.category
      target_field: category
  - set:
      field: event.dataset
      value: connector.items
  - set:
      field: "@timestamp"
      value: "{{_ingest.timestamp}}"
  - set:
      field: ecs.version
      value: "8.0.0"
